import React from 'react';
import AppItem from './AppItem';

class AppList extends React.Component {
  render() {
    return (
      <div>
      <div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Virus Trackers"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Corona Trace"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Beta"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Covid World"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"SOS"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['symptom_checker'] ? <AppItem    name={"Covidcheck"}    homepage={""}    functions={"Symptom Checker"}    platforms={"['Web']"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['symptom_checker'] ? <AppItem    name={"How We Feel"}    homepage={""}    functions={"Symptom Checker"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Citizen"}    homepage={"https://citizen.com/"}    functions={"Exposure Notification"}    platforms={"['Android', 'iOS']"}    is_free={"Yes"}    is_optin={"Not populated"}    status={"Pre-launch"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"NHSX "}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_checker'] ? <AppItem    name={"CycleBreak"}    homepage={"https://www.xperix.io/covid19"}    functions={"Exposure Notification, Symptom Checker"}    platforms={"['Web']"}    is_free={"Not populated"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not applicable"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['Business Owners']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Infection Chain"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Proof of Concept"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['immunity_passport'] ? <AppItem    name={"Covi-Id"}    homepage={""}    functions={"Immunity Passport"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Stopp Corona App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Accenture"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Covid Symptom Tracker"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['movement_tracking'] ? <AppItem    name={"Gears Malaysia App"}    homepage={""}    functions={"Exposure Notification, Movement Tracking"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"CoEpi"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"ViruSafe"}    homepage={""}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Zerobase"}    homepage={"https://www.zerobase.io/"}    functions={"Exposure Notification"}    platforms={"['iOS', 'Android']"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"Covapp"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"COVIDSafe App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"['Android', 'iOS']"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Shares.vc App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Aarogya Setu App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"CovidWatch"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Privacy Preserving Proven Prior Proximity Protocol (P6)"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"SafeMap"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"AITIA"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['lab_logistics'] && this.props.filter['manual_contact_tracing'] && this.props.filter['postcare_support'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"CommCare for COVID-19"}    homepage={"https://www.dimagi.com/covid-19/"}    functions={"Lab Logistics, Manual Contact Tracing, Postcare Support, Symptom Reporting"}    platforms={"['iOS', 'Android', 'Web']"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not applicable"}     details={"Not populated"}     state_adoption={"city of san francisco"}     target_audience={"['Healthcare Workers']"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"CRISP"}    homepage={"https://www.crisphealth.org/"}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['Healthcare Workers']"} /> : <div/>}</div>
<div>{this.props.filter['symptom_reporting'] ? <AppItem    name={"Georgia Web Portal"}    homepage={""}    functions={"Symptom Reporting"}    platforms={"['Web']"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Coronika App"}    homepage={"https://www.coronika.app"}    functions={"Exposure Notification"}    platforms={"['iOS', 'Android']"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"GH Covid-19 Tracker App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Waiting Approval"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Corona Network"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Proof of Concept"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"StopKorona! App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"HaMagen"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Cubeiq"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['information_and_statistics'] && this.props.filter['policy'] ? <AppItem    name={"#Masks4all"}    homepage={"https://masks4all.co"}    functions={"Information and Statistics, Policy"}    platforms={"['Web']"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['symptom_checker'] && this.props.filter['exposure_notification'] && this.props.filter['immunity_passport'] ? <AppItem    name={"SafePassCV / KeypassCV"}    homepage={""}    functions={"Symptom Checker, Exposure Notification, Immunity Passport"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['symptom_checker'] && this.props.filter['business_readiness'] ? <AppItem    name={"Work.com"}    homepage={"https://work.com"}    functions={"Symptom Checker, Business Readiness"}    platforms={"['Web']"}    is_free={"Not populated"}    is_optin={"Yes"}    status={"Pre-launch"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['Business Owners']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_checker'] ? <AppItem    name={"WHO Sponsored App"}    homepage={""}    functions={"Exposure Notification, Symptom Checker"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Corona GO App"}    homepage={"https://corona-go.de"}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Pandoa"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"safer.me"}    homepage={"https://www.safer.me/"}    functions={"Not populated"}    platforms={"['iOS', 'Android']"}    is_free={"Not populated"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['Business Owners']"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Cit"}    homepage={""}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Pandemic.Events"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"PathCheck (Safe Paths: PrivateKit)"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['symptom_reporting'] ? <AppItem    name={"AU Health ExpressCare"}    homepage={"https://www.augustahealth.org/default.aspx"}    functions={"Symptom Reporting"}    platforms={"['iOS', 'Android', 'Web']"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not applicable"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"BanDemic"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"CoWin-20 / Corona Kavach"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['information_and_statistics'] ? <AppItem    name={"MySejahtera App"}    homepage={""}    functions={"Information and Statistics"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Cotect"}    homepage={"https://cotect.launchaco.com"}    functions={"Exposure Notification"}    platforms={"['iOS', 'Android']"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Novid"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"Maven"}    homepage={""}    functions={"Manual Contact Tracing"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"SafeTraceAPI"}    homepage={"https://safetraceapi.org/safetrace-whitepaper/"}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"Corotrack"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Abandoned"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"Coronastatus"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"Covid-19-Track"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"HSE Covid-19 App"}    homepage={""}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Estimote"}    homepage={"https://estimote.com/wearables"}    functions={"Exposure Notification"}    platforms={"['IOT']"}    is_free={"Not populated"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['Business Owners']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"Coronatrace"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"Telegram CT"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Proposal"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"CrowdsourceRescue"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['information_and_statistics'] ? <AppItem    name={"Corona Map Saudi Arabi App"}    homepage={""}    functions={"Information and Statistics"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"CoronApp"}    homepage={""}    functions={"Exposure Notification"}    platforms={"['HUAWEI AppGallery']"}    is_free={"Yes"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Coalition"}    homepage={"https://www.coalitionnetwork.org"}    functions={"Not populated"}    platforms={"['iOS', 'Android']"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Covid-App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['immunity_passport'] ? <AppItem    name={"CoronaPass"}    homepage={""}    functions={"Immunity Passport"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"SaraAlert"}    homepage={""}    functions={"Manual Contact Tracing"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Coronamap"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"MyLog14"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['immunity_passport'] ? <AppItem    name={"CovidCred"}    homepage={""}    functions={"Immunity Passport"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"Salesforce"}    homepage={""}    functions={"Manual Contact Tracing"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Corona Data Scraper"}    homepage={""}    functions={"Exposure Notification"}    platforms={"['Web']"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"FeverMap"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"Sneeze Map"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"MIT Safe Paths"}    homepage={"https://covidsafepaths.org"}    functions={"Exposure Notification"}    platforms={"['Web', 'Smartphone']"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['manual_contact_tracing'] && this.props.filter['locate_testing_centers'] && this.props.filter['lab_logistics'] ? <AppItem    name={"Healthy Together"}    homepage={"http://healthytogether.io/"}    functions={"Exposure Notification, Manual Contact Tracing, Locate Testing Centers, Lab Logistics"}    platforms={"['iOS', 'Android']"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"As of April 27, at least 30,000 people had downloaded the Healthy Together app—less than 1 percent of the state’s population."}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"EH: Africa CT Solution"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Ghana Health Services App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Merit"}    homepage={""}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"NextTrace"}    homepage={""}    functions={"Manual Contact Tracing"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Safetrace"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Code Orange"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"Redpad"}    homepage={""}    functions={"Manual Contact Tracing"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Private Tracer"}    homepage={""}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Not populated"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"eRouska (eFacemask) App"}    homepage={""}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Mask.ir "}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Smittestopp App"}    homepage={""}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Alipay App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Trace Together"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"BeAware Bahrain App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Care19"}    homepage={"https://ndresponse.gov/covid-19-resources/care19"}    functions={"Exposure Notification"}    platforms={"['iOS', 'Android']"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Planned"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Nextstrain"}    homepage={""}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['symptom_checker'] && this.props.filter['information_and_statistics'] ? <AppItem    name={"COVID Symptom Study"}    homepage={"https://covid.joinzoe.com/"}    functions={"Symptom Checker, Information and Statistics"}    platforms={"['iOS', 'Android']"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"Twilio"}    homepage={""}    functions={"Manual Contact Tracing"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"CovidSafe"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"['Android', 'iOS']"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Planned with Jurisdiction Support"}     details={"Not populated"}     state_adoption={"Picked by State of Washington as their exposure notification app"}     target_audience={"['General Public']"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Mila "}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Memiah"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Proof of Concept"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"GeoHealth"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Swiss Contact Tracing App"}    homepage={""}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"In Development"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] && this.props.filter['symptom_reporting'] ? <AppItem    name={"Covid Near You"}    homepage={""}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Proof of Concept"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"MyTrace App"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Released"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Test and Trace"}    homepage={""}    functions={"Not populated"}    platforms={"['Web']"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Gesund  Zusammen"}    homepage={""}    functions={"Exposure Notification"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Unknown"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Covid Flutter"}    homepage={"https://www.youtube.com/watch?v=rfP8iQoqJnc"}    functions={"Not populated"}    platforms={"Not populated"}    is_free={"Not populated"}    is_optin={"Not populated"}    status={"Abandoned"}    en_api={"Not populated"}     details={"Not populated"}     state_adoption={"Not populated"}     target_audience={"Not populated"} /> : <div/>}</div>
      </div>
    );
  }
}

export default AppList;
