import React from 'react';
import AppItem from './AppItem';

class AppList extends React.Component {
  render() {
    return (
      <div>
<div>{this.props.filter['lab_logistics'] || this.props.filter['manual_contact_tracing'] || this.props.filter['postcare_support'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"CommCare for COVID-19"}    homepage={"https://www.dimagi.com/covid-19/"}    details={`This app offers screening and triage protocols. It also provides contact-tracing capabilities and the ability to disseminate information, along with lab-tracking and logistics services.`}    functions={"Lab Logistics, Manual Contact Tracing, Postcare Support, Symptom Reporting"}    platforms={"iOS, Android, Web"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not applicable"}     state_adoption={"city of san francisco"}     target_audience={"Healthcare Workers"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['manual_contact_tracing'] || this.props.filter['locate_testing_centers'] || this.props.filter['lab_logistics'] ? <AppItem    name={"Healthy Together"}    homepage={"http://healthytogether.io/"}    details={`Using data compiled by Healthy Together, public health officials will be able to access a list of contacts and past locations when individuals test positive. Users can also check their symptoms and find testing centers.`}    functions={"Exposure Notification, Manual Contact Tracing, Locate Testing Centers, Lab Logistics"}    platforms={"iOS, Android"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"As of April 27, at least 30,000 people had downloaded the Healthy Together app—less than 1 percent of the state’s population."}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Care19"}    homepage={"https://ndresponse.gov/covid-19-resources/care19"}    details={`Once the app is downloaded, individuals will be given a random ID number and the app will anonymously cache the individual’s locations throughout the day. Individuals are then encouraged to categorize their movement into different groups such as work or grocery.`}    functions={"Exposure Notification"}    platforms={"iOS, Android"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Planned"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['symptom_reporting'] ? <AppItem    name={"AU Health ExpressCare"}    homepage={"https://www.augustahealth.org/default.aspx"}    details={`This app allows people to be screened by a medical clinician via video chat or phone. Those with symptoms that meet the criteria to warrant a coronavirus test - along with first responders, health workers and other high-risk individuals - will receive an appointment at the nearest state testing center.`}    functions={"Symptom Reporting"}    platforms={"iOS, Android, Web"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not applicable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Zerobase"}    homepage={"https://www.zerobase.io/"}    details={`Zerobase’s contact-tracing technology anonymously analyzes community networks of interaction to identify people who visited the same places at roughly the same times. When individuals are tested, Zerobase constructs a list of potentially exposed contacts.`}    functions={"Exposure Notification"}    platforms={"iOS, Android"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"MIT Safe Paths"}    homepage={"https://covidsafepaths.org"}    details={`MIT’s Safe Paths platform involves a smartphone application, PrivateKit, and a web application, Safe Places. PrivateKit will enable users to match location data on their smartphones with anonymized, redacted, and blurred location history of infected patients. Overlapped GPS and Bluetooth trails allow individuals to check if they have crossed paths with people who were diagnosed positive for the virus.`}    functions={"Exposure Notification"}    platforms={"Web, Smartphone"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_checker'] ? <AppItem    name={"CycleBreak"}    homepage={"https://www.xperix.io/covid19"}    details={`CycleBreak assists businesses in monitoring the status of employees and their interactions with other people and objects in the workplace. By tracing employees in a time-based order, the CycleBreak program can immediately produce reports on contacts of infected employees. That enables contacts to begin isolating and monitoring for coronavirus symptoms right away.`}    functions={"Exposure Notification, Symptom Checker"}    platforms={"Web"}    is_free={"Data Unavailable"}    is_optin={"Yes"}    status={"Released"}    en_api={"Not applicable"}     state_adoption={"Data Unavailable"}     target_audience={"Business Owners"} /> : <div/>}</div>
<div>{this.props.filter['symptom_checker'] || this.props.filter['business_readiness'] ? <AppItem    name={"Work.com"}    homepage={"https://work.com"}    details={`Salesforce’s Work.com app is designed to help businesses track the health of their employees and adjust work schedules to maintain appropriate social distancing. Additionally, the web-based app will have a resource center with information and guidance from health experts and business leaders. There are plans to add a contract-tracing feature so that companies can contact employees who were around sick co-workers.`}    functions={"Symptom Checker, Business Readiness"}    platforms={"Web"}    is_free={"Data Unavailable"}    is_optin={"Yes"}    status={"Pre-launch"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Business Owners"} /> : <div/>}</div>
<div>{this.props.filter['symptom_reporting'] ? <AppItem    name={"Georgia Web Portal"}    homepage={""}    details={`The Georgia state government is currently pilot testing a web-based contact-tracing app. Users can self-report their health information to the state’s health department to enhance monitoring and contact tracing.`}    functions={"Symptom Reporting"}    platforms={"Web"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Estimote"}    homepage={"https://estimote.com/wearables"}    details={`Estimote offers businesses the ability to do proximity tracking with dwell time for employees, facilitating contact tracing and alerting. The system uses small wireless devices that automatically register close interactions between employees and feed the data to a central dashboard for contact tracing.`}    functions={"Exposure Notification"}    platforms={"IOT"}    is_free={"Data Unavailable"}    is_optin={"Yes"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Business Owners"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Coalition"}    homepage={"https://www.coalitionnetwork.org"}    details={`The Coalition app alerts users when they have come into contact with people showing symptoms or infected. If users are infected or symptomatic, the app also alerts their contacts. Coalition's Whisper Tracing, an open and privacy-first protocol, randomizes a user's device identity and does not share identifiable information.`}    functions={"Data Unavailable"}    platforms={"iOS, Android"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Citizen"}    homepage={"https://citizen.com/"}    details={`Uses Existing App to collect information`}    functions={"Exposure Notification"}    platforms={"Android, iOS"}    is_free={"Yes"}    is_optin={"Data Unavailable"}    status={"Pre-launch"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['symptom_checker'] || this.props.filter['information_and_statistics'] ? <AppItem    name={"COVID Symptom Study"}    homepage={"https://covid.joinzoe.com/"}    details={`Help slow the spread of COVID-19 by self-reporting your symptoms daily, even if you feel well.

Join millions of people supporting scientists at Stanford University, Harvard University, Massachusetts General Hospital, and King's College London to help fight coronavirus by identifying:

\* How fast the virus is spreading in your area
\* High-risk areas in the US
\* Who is most at risk, by better understanding symptoms linked to underlying health conditions

You will contribute to advance research on COVID-19 in partnership with leading health researchers globally like TwinsUK, one of the most clinically detailed studies in the world.

This app (formerly known as the Covid Symptom Tracker) allows you to help others, but does not give health advice. If you need health advice please visit the CDC website at: https://www.cdc.gov/coronavirus/2019-ncov/index.html

This app has been designed for everyone to report their status not just those who are ill.

It was designed by doctors and scientists at King's College London, Guys and St Thomas’ Hospitals and Zoe Global Limited, a health technology company.

In the US the app is being used by the Nurses' Health Study to identify symptoms in active healthcare workers who are treating people with COVID across the country and risking their own health to help us.

In response to recommendations by Stand Up To Cancer (SU2C), the app also includes questions for cancer patients and survivors, such as if they are living with cancer, what type of cancer and what treatment they are receiving.

If you would like to help out in this difficult time, then you can. Download the app and share daily your own status, even if you are well. With your help we can understand much better the situation across the nation, how the disease presents itself to different people, and how it progresses.

This is a new virus which the world has never seen before. There are a wide range of symptoms, which differ between people. With your help we can understand better how the disease presents itself depending upon individual factors such as health and age.

No information you share will be used for commercial purposes.

There are two parts to the app:

HEALTH INFORMATION
You will be asked to share some general information, such as your age and some health details, such as whether you have certain diseases.

SYMPTOM TRACKING
We will ask you every day to let us know how you feel, so you can share your symptoms. We will also ask whether you have visited the hospital, what treatment you received there, and whether you have been tested for COVID-19 (Coronavirus).`}    functions={"Symptom Checker, Information and Statistics"}    platforms={"iOS, Android"}    is_free={"Yes"}    is_optin={"Yes"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"safer.me"}    homepage={"https://www.safer.me/"}    details={`Safer.me is a business-oriented app that automatically logs workers’ contact information without sharing their locations. The objective is to help businesses respond quickly to symptoms, keeping employees and customers safe from exposure.`}    functions={"Data Unavailable"}    platforms={"iOS, Android"}    is_free={"Data Unavailable"}    is_optin={"Yes"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Business Owners"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"CovidSafe"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Android, iOS"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Planned with Jurisdiction Support"}     state_adoption={"Picked by State of Washington as their exposure notification app"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['information_and_statistics'] || this.props.filter['policy'] ? <AppItem    name={"#Masks4all"}    homepage={"https://masks4all.co"}    details={`Website provides information and explanation about the importance of wearing masks and the impact it has on the spread and curve of COVID. The site also includes how to use and clean reusable cloth masks. Additionally the protocol of mask wearing in individual countries.`}    functions={"Information and Statistics, Policy"}    platforms={"Web"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Cotect"}    homepage={"https://cotect.launchaco.com"}    details={`Anonymous reporting, infection alerts, symptom checks`}    functions={"Exposure Notification"}    platforms={"iOS, Android"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Coronika App"}    homepage={"https://www.coronika.app"}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"iOS, Android"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"CoronApp"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"HUAWEI AppGallery"}    is_free={"Yes"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"CoEpi"}    homepage={""}    details={`CoEpi relies on voluntary symptom sharing. The system notifies users about potential exposures based on Bluetooth proximity-based exposures.`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"CRISP"}    homepage={"https://www.crisphealth.org/"}    details={`The CRISP system helps patients who test positive for the virus make appointments. Data from the system can be used for contact tracing.`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Healthcare Workers"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_checker'] ? <AppItem    name={"WHO Sponsored App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Symptom Checker"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Virus Trackers"}    homepage={""}    details={`Directory of projects working on on privacy-preserving contact tracing and exposure notification for COVID-19`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"Telegram CT"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Proposal"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Stopp Corona App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Shares.vc App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"SafeTraceAPI"}    homepage={"https://safetraceapi.org/safetrace-whitepaper/"}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"SOS"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Novid"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['symptom_checker'] ? <AppItem    name={"How We Feel"}    homepage={""}    details={`Data Unavailable`}    functions={"Symptom Checker"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"General Public"} /> : <div/>}</div>
<div>{this.props.filter['symptom_checker'] ? <AppItem    name={"Covidcheck"}    homepage={""}    details={`Data Unavailable`}    functions={"Symptom Checker"}    platforms={"Web"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"CovidWatch"}    homepage={""}    details={`Covid Watch takes anonymous reports of positive tests for the coronavirus and broadcasts alerts to the infected party’s contacts. Contact lists are based on Bluetooth signals shared between app users’ smartphones.`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"Covid-19-Track"}    homepage={""}    details={`Care19 assigns individuals random ID numbers so the app can anonymously cache their locations throughout the day. Users are encouraged to categorize their movements into different groups, such as work or grocery. State agencies can use the information to aid in contact tracing.`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Corona Data Scraper"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Web"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"COVIDSafe App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Android, iOS"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"ViruSafe"}    homepage={""}    details={`ViruSafe gives users the ability to track their symptoms and health status daily, which in turn gives Ministry of Health a good overview of the spread of the pandemic. Users can also voluntarily share their location to enable institutions to act accordingly, in case of an emergency.`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"Twilio"}    homepage={""}    details={`Data Unavailable`}    functions={"Manual Contact Tracing"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Trace Together"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Test and Trace"}    homepage={""}    details={`Data Unavailable`}    functions={"Data Unavailable"}    platforms={"Web"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"StopKorona! App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"Sneeze Map"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"SaraAlert"}    homepage={""}    details={`Data Unavailable`}    functions={"Manual Contact Tracing"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"Salesforce"}    homepage={""}    details={`Data Unavailable`}    functions={"Manual Contact Tracing"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Safetrace"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['symptom_checker'] || this.props.filter['exposure_notification'] || this.props.filter['immunity_passport'] ? <AppItem    name={"SafePassCV / KeypassCV"}    homepage={""}    details={`Data Unavailable`}    functions={"Symptom Checker, Exposure Notification, Immunity Passport"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"SafeMap"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"Redpad"}    homepage={""}    details={`Data Unavailable`}    functions={"Manual Contact Tracing"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Privacy Preserving Proven Prior Proximity Protocol (P6)"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"PathCheck (Safe Paths: PrivateKit)"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Pandoa"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Pandemic.Events"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"NextTrace"}    homepage={""}    details={`Data Unavailable`}    functions={"Manual Contact Tracing"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"NHSX "}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"MyTrace App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['information_and_statistics'] ? <AppItem    name={"MySejahtera App"}    homepage={""}    details={`Data Unavailable`}    functions={"Information and Statistics"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"MyLog14"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Mila "}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Memiah"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Proof of Concept"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['manual_contact_tracing'] ? <AppItem    name={"Maven"}    homepage={""}    details={`Data Unavailable`}    functions={"Manual Contact Tracing"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Mask.ir "}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Infection Chain"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Proof of Concept"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"HaMagen"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Ghana Health Services App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Gesund  Zusammen"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"GeoHealth"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['movement_tracking'] ? <AppItem    name={"Gears Malaysia App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Movement Tracking"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"GH Covid-19 Tracker App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Waiting Approval"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"FeverMap"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"EH: Africa CT Solution"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Cubeiq"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"CrowdsourceRescue"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['immunity_passport'] ? <AppItem    name={"CovidCred"}    homepage={""}    details={`Data Unavailable`}    functions={"Immunity Passport"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Covid-App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Covid World"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Covid Symptom Tracker"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"Covid Near You"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Proof of Concept"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['immunity_passport'] ? <AppItem    name={"Covi-Id"}    homepage={""}    details={`Data Unavailable`}    functions={"Immunity Passport"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"Covapp"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"Corotrack"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Abandoned"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"Coronatrace"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"Coronastatus"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Coronamap"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['immunity_passport'] ? <AppItem    name={"CoronaPass"}    homepage={""}    details={`Data Unavailable`}    functions={"Immunity Passport"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Corona Trace"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Beta"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Corona Network"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Proof of Concept"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['information_and_statistics'] ? <AppItem    name={"Corona Map Saudi Arabi App"}    homepage={""}    details={`Data Unavailable`}    functions={"Information and Statistics"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Corona GO App"}    homepage={"https://corona-go.de"}    details={`Data Unavailable`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Code Orange"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"CoWin-20 / Corona Kavach"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"BeAware Bahrain App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"BanDemic"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Alipay App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Accenture"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] ? <AppItem    name={"Aarogya Setu App"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{this.props.filter['exposure_notification'] || this.props.filter['symptom_reporting'] ? <AppItem    name={"AITIA"}    homepage={""}    details={`Data Unavailable`}    functions={"Exposure Notification, Symptom Reporting"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Released"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"eRouska (eFacemask) App"}    homepage={""}    details={`Data Unavailable`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Swiss Contact Tracing App"}    homepage={""}    details={`Data Unavailable`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Smittestopp App"}    homepage={""}    details={`Data Unavailable`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Private Tracer"}    homepage={""}    details={`Data Unavailable`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Data Unavailable"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Nextstrain"}    homepage={""}    details={`Data Unavailable`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Merit"}    homepage={""}    details={`Data Unavailable`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"HSE Covid-19 App"}    homepage={""}    details={`Data Unavailable`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"In Development"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>
<div>{false ? <AppItem    name={"Cit"}    homepage={""}    details={`Data Unavailable`}    functions={"Data Unavailable"}    platforms={"Data Unavailable"}    is_free={"Data Unavailable"}    is_optin={"Data Unavailable"}    status={"Unknown"}    en_api={"Data Unavailable"}     state_adoption={"Data Unavailable"}     target_audience={"Data Unavailable"} /> : <div/>}</div>

      </div>
    );
  }
}

export default AppList;
